/* This source file is generated by mkimages.py. */
#define IMAGE_NONE     0
#define IMAGE_STUCK    1
#define IMAGE_DONE     2
#define IMAGE_BOOKMARK 3
#define IMAGE_WRITE    4
#define IMAGE_CHECK    5
#define IMAGE_STAR     6
