/* This source file is generated by mkimages.py. */
#define IMAGE_NONE    0
#define IMAGE_QUIT    1
#define IMAGE_BACK    2
#define IMAGE_HELP    3
#define IMAGE_OPTIONS 4
#define IMAGE_CLIP    5
#define IMAGE_PLAY    6
#define IMAGE_PREV    7
#define IMAGE_RANDOM  8
#define IMAGE_NEXT    9
